
package view;

import controller.ProjectController;
import controller.TaskController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Project;
import model.Task;
import util.ButtonColumnCellRenderer;
import util.DueDateRenderer;
import util.TaskTableModel;

/**
 *
 * @author amandasilva
 */
public class MainScreen extends javax.swing.JFrame {

    ProjectController projectController;
    TaskController taskController;
//    esta atrelado ao jList
    DefaultListModel projectsModel;
    
    TaskTableModel taskTableModel;
        
    public MainScreen() throws SQLException {
        initComponents();
        
        initDataController();
        
        initComponentsModel();
        
        decorateTableTask();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSPTaskList = new javax.swing.JScrollPane();
        jTableTaskList = new javax.swing.JTable();
        jPToolbar = new javax.swing.JPanel();
        jLToolbarTitle = new javax.swing.JLabel();
        jLToolbarSubTitle = new javax.swing.JLabel();
        jPProjects = new javax.swing.JPanel();
        jLProjectsTitle = new javax.swing.JLabel();
        jLProjectsAdd = new javax.swing.JLabel();
        jPTasks = new javax.swing.JPanel();
        jLTasksTitle = new javax.swing.JLabel();
        jLTasksAdd = new javax.swing.JLabel();
        jPProjectsList = new javax.swing.JPanel();
        jSPProjects = new javax.swing.JScrollPane();
        jLProjectsList = new javax.swing.JList<>();
        jPTaskList = new javax.swing.JPanel();
        jPEmptyList = new javax.swing.JPanel();
        jLEmptyListIcon = new javax.swing.JLabel();
        jLEmptyListTitle = new javax.swing.JLabel();
        jLEmptyListSubTitle = new javax.swing.JLabel();

        jTableTaskList.setBackground(new java.awt.Color(255, 255, 255));
        jTableTaskList.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTableTaskList.setForeground(new java.awt.Color(0, 0, 0));
        jTableTaskList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa Concluída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTaskList.setGridColor(new java.awt.Color(255, 255, 255));
        jTableTaskList.setRowHeight(50);
        jTableTaskList.setRowMargin(10);
        jTableTaskList.setSelectionBackground(new java.awt.Color(204, 255, 204));
        jTableTaskList.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTableTaskList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableTaskList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableTaskList.setShowGrid(false);
        jTableTaskList.setShowHorizontalLines(true);
        jTableTaskList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTaskListMouseClicked(evt);
            }
        });
        jSPTaskList.setViewportView(jTableTaskList);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 800));

        jPToolbar.setBackground(new java.awt.Color(51, 147, 88));

        jLToolbarTitle.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLToolbarTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLToolbarTitle.setIcon(new javax.swing.ImageIcon("/Users/amandasilva/Documents/Geral/01-Capgemini/LA3/Materiais Compartilhados/resources/check-sign.png")); // NOI18N
        jLToolbarTitle.setText(" Todo App");

        jLToolbarSubTitle.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLToolbarSubTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLToolbarSubTitle.setText("Anote tudo, nao esqueça de nada");

        javax.swing.GroupLayout jPToolbarLayout = new javax.swing.GroupLayout(jPToolbar);
        jPToolbar.setLayout(jPToolbarLayout);
        jPToolbarLayout.setHorizontalGroup(
            jPToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLToolbarTitle)
                    .addComponent(jLToolbarSubTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPToolbarLayout.setVerticalGroup(
            jPToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPToolbarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLToolbarTitle)
                .addGap(18, 18, 18)
                .addComponent(jLToolbarSubTitle)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPProjects.setBackground(new java.awt.Color(255, 255, 255));

        jLProjectsTitle.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLProjectsTitle.setForeground(new java.awt.Color(51, 147, 88));
        jLProjectsTitle.setText("Projetos");

        jLProjectsAdd.setIcon(new javax.swing.ImageIcon("/Users/amandasilva/Documents/Geral/01-Capgemini/LA3/Materiais Compartilhados/resources/add.png")); // NOI18N
        jLProjectsAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLProjectsAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPProjectsLayout = new javax.swing.GroupLayout(jPProjects);
        jPProjects.setLayout(jPProjectsLayout);
        jPProjectsLayout.setHorizontalGroup(
            jPProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLProjectsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLProjectsAdd)
                .addContainerGap())
        );
        jPProjectsLayout.setVerticalGroup(
            jPProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProjectsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPProjectsLayout.createSequentialGroup()
                        .addComponent(jLProjectsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPProjectsLayout.createSequentialGroup()
                        .addComponent(jLProjectsAdd)
                        .addGap(15, 15, 15))))
        );

        jPTasks.setBackground(new java.awt.Color(255, 255, 255));

        jLTasksTitle.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLTasksTitle.setForeground(new java.awt.Color(51, 147, 88));
        jLTasksTitle.setText("Tarefas");

        jLTasksAdd.setIcon(new javax.swing.ImageIcon("/Users/amandasilva/Documents/Geral/01-Capgemini/LA3/Materiais Compartilhados/resources/add.png")); // NOI18N
        jLTasksAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLTasksAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPTasksLayout = new javax.swing.GroupLayout(jPTasks);
        jPTasks.setLayout(jPTasksLayout);
        jPTasksLayout.setHorizontalGroup(
            jPTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTasksTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLTasksAdd)
                .addContainerGap())
        );
        jPTasksLayout.setVerticalGroup(
            jPTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTasksTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTasksLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLTasksAdd)
                .addGap(15, 15, 15))
        );

        jPProjectsList.setBackground(new java.awt.Color(255, 255, 255));

        jSPProjects.setForeground(new java.awt.Color(0, 0, 0));

        jLProjectsList.setBackground(new java.awt.Color(255, 255, 255));
        jLProjectsList.setBorder(null);
        jLProjectsList.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLProjectsList.setForeground(new java.awt.Color(0, 0, 0));
        jLProjectsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jLProjectsList.setFixedCellHeight(50);
        jLProjectsList.setSelectionBackground(new java.awt.Color(51, 147, 88));
        jLProjectsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLProjectsListMouseClicked(evt);
            }
        });
        jSPProjects.setViewportView(jLProjectsList);

        javax.swing.GroupLayout jPProjectsListLayout = new javax.swing.GroupLayout(jPProjectsList);
        jPProjectsList.setLayout(jPProjectsListLayout);
        jPProjectsListLayout.setHorizontalGroup(
            jPProjectsListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProjectsListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSPProjects)
                .addContainerGap())
        );
        jPProjectsListLayout.setVerticalGroup(
            jPProjectsListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProjectsListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSPProjects)
                .addContainerGap())
        );

        jPTaskList.setBackground(new java.awt.Color(255, 255, 255));
        jPTaskList.setLayout(new java.awt.BorderLayout());

        jPEmptyList.setBackground(new java.awt.Color(255, 255, 255));

        jLEmptyListIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLEmptyListIcon.setIcon(new javax.swing.ImageIcon("/Users/amandasilva/Documents/Geral/01-Capgemini/LA3/Materiais Compartilhados/resources/lists.png")); // NOI18N
        jLEmptyListIcon.setToolTipText("");

        jLEmptyListTitle.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLEmptyListTitle.setForeground(new java.awt.Color(51, 147, 88));
        jLEmptyListTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLEmptyListTitle.setText("Nenhuma tarefa por aqui :D");

        jLEmptyListSubTitle.setBackground(new java.awt.Color(204, 204, 204));
        jLEmptyListSubTitle.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLEmptyListSubTitle.setForeground(new java.awt.Color(153, 153, 153));
        jLEmptyListSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLEmptyListSubTitle.setText("Clique no botão \"+\" para adicionar uma nova tarefa");

        javax.swing.GroupLayout jPEmptyListLayout = new javax.swing.GroupLayout(jPEmptyList);
        jPEmptyList.setLayout(jPEmptyListLayout);
        jPEmptyListLayout.setHorizontalGroup(
            jPEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEmptyListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLEmptyListIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLEmptyListTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLEmptyListSubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPEmptyListLayout.setVerticalGroup(
            jPEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEmptyListLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLEmptyListIcon)
                .addGap(28, 28, 28)
                .addComponent(jLEmptyListTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLEmptyListSubTitle)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jPTaskList.add(jPEmptyList, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPProjectsList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPTaskList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPProjectsList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPTaskList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLProjectsAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLProjectsAddMouseClicked
        // TODO add your handling code here:
        ProjectDialogScreen projectDialogScreen = new ProjectDialogScreen(this, rootPaneCheckingEnabled);
        projectDialogScreen.setVisible(true);
        
        projectDialogScreen.addWindowListener(new WindowAdapter(){
            public void windowClosed(WindowEvent e) {
                try {
                    loadProjects();
                } catch (SQLException ex) {
                    Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }//GEN-LAST:event_jLProjectsAddMouseClicked

    private void jLTasksAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTasksAddMouseClicked
        // TODO add your handling code here:
        
        int indexSeletecProject = jLProjectsList.getSelectedIndex();
        if (indexSeletecProject != -1) {
            TaskDialogScreen taskDialogScreen = new TaskDialogScreen(this, true);

            Project project = (Project) projectsModel.get(jLProjectsList.getSelectedIndex());

            taskDialogScreen.setProject(project);
            taskDialogScreen.setVisible(true);

            taskDialogScreen.addWindowListener(new WindowAdapter() {
                public void windowClosed(WindowEvent e) {
                    int projectIndex = jLProjectsList.getSelectedIndex();
                    Project project = (Project) projectsModel.get(projectIndex);
                    try {
                        loadTasks(project.getId());
                    } catch (SQLException ex) {
                        Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
        } else {
            JOptionPane.showMessageDialog(rootPane, "Voc� deve escolher um projeto para essa tarefa", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLTasksAddMouseClicked

    private void jTableTaskListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTaskListMouseClicked
        try {
            // TODO add your handling code here:
            int rowIndex = jTableTaskList.rowAtPoint(evt.getPoint());
            int columnIndex = jTableTaskList.columnAtPoint(evt.getPoint());
            Task task = taskTableModel.getTasks().get(rowIndex);
            
            switch (columnIndex) {
                case 1:
                    break;
                case 3:
                    taskController.update(task);
                    break;
                case 4:
                    JOptionPane.showMessageDialog(rootPane, "Editar a tarefa");
                    break;
                case 5:
                    taskController.deleteById(task.getId());
                    taskTableModel.getTasks().remove(task);

                    int projectIndex = jLProjectsList.getSelectedIndex();
                    Project project = (Project) projectsModel.get(projectIndex);
                    loadTasks(project.getId());
                    break;
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTableTaskListMouseClicked

    private void jLProjectsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLProjectsListMouseClicked
        // TODO add your handling code here:
        int projectIndex = jLProjectsList.getSelectedIndex();
        
        Project project = (Project)projectsModel.get(projectIndex);
        try {
            loadTasks(project.getId());
        } catch (SQLException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLProjectsListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainScreen().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLEmptyListIcon;
    private javax.swing.JLabel jLEmptyListSubTitle;
    private javax.swing.JLabel jLEmptyListTitle;
    private javax.swing.JLabel jLProjectsAdd;
    private javax.swing.JList<String> jLProjectsList;
    private javax.swing.JLabel jLProjectsTitle;
    private javax.swing.JLabel jLTasksAdd;
    private javax.swing.JLabel jLTasksTitle;
    private javax.swing.JLabel jLToolbarSubTitle;
    private javax.swing.JLabel jLToolbarTitle;
    private javax.swing.JPanel jPEmptyList;
    private javax.swing.JPanel jPProjects;
    private javax.swing.JPanel jPProjectsList;
    private javax.swing.JPanel jPTaskList;
    private javax.swing.JPanel jPTasks;
    private javax.swing.JPanel jPToolbar;
    private javax.swing.JScrollPane jSPProjects;
    private javax.swing.JScrollPane jSPTaskList;
    private javax.swing.JTable jTableTaskList;
    // End of variables declaration//GEN-END:variables

    public void decorateTableTask(){
        
//        customizando o header da table de tarefas
        jTableTaskList.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 12));
        jTableTaskList.getTableHeader().setBackground(new Color(51, 147, 88));
        jTableTaskList.getTableHeader().setForeground(new Color(255, 255, 255));

        jTableTaskList.getColumnModel().getColumn(2).setCellRenderer(new DueDateRenderer());
        
        jTableTaskList.getColumnModel().getColumn(4).setCellRenderer(new ButtonColumnCellRenderer("edit"));
        jTableTaskList.getColumnModel().getColumn(5).setCellRenderer(new ButtonColumnCellRenderer("delete"));
        
                
//        criando um sort automatico para as colunas da table
//        jTableTaskList.setAutoCreateRowSorter(true);
        
    }
    
    public void initDataController(){
        projectController = new ProjectController();
        taskController = new TaskController();
        
    }
    
    public void initComponentsModel() throws SQLException{
        projectsModel = new DefaultListModel();
        loadProjects();
        
        taskTableModel = new TaskTableModel();
        jTableTaskList.setModel(taskTableModel);
        
        if(!projectsModel.isEmpty()){
            jLProjectsList.setSelectedIndex(0);
            int projectIndex = jLProjectsList.getSelectedIndex();
            Project project = (Project)projectsModel.get(projectIndex);
            loadTasks(project.getId());
        }
        
    }
    
    public void loadTasks(int project_id) throws SQLException{
        List<Task> tasks = taskController.getAll(project_id);
        
        taskTableModel.setTasks(tasks);
        showJTableTasks(!tasks.isEmpty());
        
    }
    
    private void showJTableTasks(boolean hasTasks){
        if(hasTasks) {
            if(jPEmptyList.isVisible()){
                jPEmptyList.setVisible(false);
                jPTaskList.remove(jPEmptyList);
            }
            
            jPTaskList.add(jSPTaskList);
            jSPTaskList.setVisible(true);
            jSPTaskList.setSize(jPTaskList.getWidth(), jPTaskList.getHeight());
        } else {
            if(jSPTaskList.isVisible()){
                jSPTaskList.setVisible(false);
                jPTaskList.remove(jSPTaskList);
            }
            
            jPTaskList.add(jPEmptyList);
            jPEmptyList.setVisible(true);
            jPEmptyList.setSize(jPTaskList.getWidth(), jPTaskList.getHeight());
        }
    }
    
    public void loadProjects() throws SQLException{
        List<Project> projects = projectController.getAll();
        projectsModel.clear();
        
        for (int i = 0; i < projects.size(); i++) {
            Project project = projects.get(i);
            projectsModel.addElement(project);
        }
        
        jLProjectsList.setModel(projectsModel);
        
    }
}
