package view;

import controller.ProjectController;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Project;

/**
 *
 * @author amandasilva
 */
public class ProjectDialogScreen extends javax.swing.JDialog {

    ProjectController projectController;
    
    public ProjectDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        projectController = new ProjectController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPToolbar = new javax.swing.JPanel();
        jLProject = new javax.swing.JLabel();
        jLProjectSave = new javax.swing.JLabel();
        jPAddProject = new javax.swing.JPanel();
        jLProjectName = new javax.swing.JLabel();
        jTFProjectName = new javax.swing.JTextField();
        jLProjectDescription = new javax.swing.JLabel();
        jSPProjectDescription = new javax.swing.JScrollPane();
        jTAProjectDescription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPToolbar.setBackground(new java.awt.Color(51, 147, 88));

        jLProject.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLProject.setForeground(new java.awt.Color(255, 255, 255));
        jLProject.setText(" Projeto");

        jLProjectSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLProjectSave.setIcon(new javax.swing.ImageIcon("/Users/amandasilva/Documents/Geral/01-Capgemini/LA3/Materiais Compartilhados/resources/check.png")); // NOI18N
        jLProjectSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLProjectSaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPToolbarLayout = new javax.swing.GroupLayout(jPToolbar);
        jPToolbar.setLayout(jPToolbarLayout);
        jPToolbarLayout.setHorizontalGroup(
            jPToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLProject, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLProjectSave, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPToolbarLayout.setVerticalGroup(
            jPToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLProjectSave, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPAddProject.setBackground(new java.awt.Color(255, 255, 255));

        jLProjectName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLProjectName.setText("Nome");

        jTFProjectName.setBackground(new java.awt.Color(255, 255, 255));
        jTFProjectName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jLProjectDescription.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLProjectDescription.setText("Descrição");

        jTAProjectDescription.setBackground(new java.awt.Color(255, 255, 255));
        jTAProjectDescription.setColumns(20);
        jTAProjectDescription.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTAProjectDescription.setRows(5);
        jSPProjectDescription.setViewportView(jTAProjectDescription);

        javax.swing.GroupLayout jPAddProjectLayout = new javax.swing.GroupLayout(jPAddProject);
        jPAddProject.setLayout(jPAddProjectLayout);
        jPAddProjectLayout.setHorizontalGroup(
            jPAddProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAddProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPAddProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSPProjectDescription)
                    .addComponent(jLProjectName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFProjectName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLProjectDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPAddProjectLayout.setVerticalGroup(
            jPAddProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAddProjectLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLProjectName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLProjectDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSPProjectDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPAddProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPAddProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLProjectSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLProjectSaveMouseClicked
        try {
            // TODO add your handling code here:
            
            if(!jTFProjectName.getText().equals("")){
                Project project = new Project();
                project.setName(jTFProjectName.getText());
                project.setDescription(jTAProjectDescription.getText());
                project.setCreatedAt(new Date());
                project.setUpdatedAt(new Date());
                projectController.save(project);
                JOptionPane.showMessageDialog(rootPane, "Projeto salvo com sucesso!!");
                // fechar a tela
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "O projeto não foi salvo, campo nome é obrigatório!!");
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }

    }//GEN-LAST:event_jLProjectSaveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProjectDialogScreen dialog = new ProjectDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLProject;
    private javax.swing.JLabel jLProjectDescription;
    private javax.swing.JLabel jLProjectName;
    private javax.swing.JLabel jLProjectSave;
    private javax.swing.JPanel jPAddProject;
    private javax.swing.JPanel jPToolbar;
    private javax.swing.JScrollPane jSPProjectDescription;
    private javax.swing.JTextArea jTAProjectDescription;
    private javax.swing.JTextField jTFProjectName;
    // End of variables declaration//GEN-END:variables
}
