
package view;

import controller.TaskController;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Project;
import model.Task;

/**
 *
 * @author amandasilva
 */
public class TaskDialogScreen extends javax.swing.JDialog {

    
    TaskController taskController;
    
    Project project;
    
    public TaskDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        hideErrorFields();
        
        taskController = new TaskController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPTaskToolbar = new javax.swing.JPanel();
        jLTask = new javax.swing.JLabel();
        jLAddTask = new javax.swing.JLabel();
        jPTaskInfos = new javax.swing.JPanel();
        JLTaskName = new javax.swing.JLabel();
        jTFTaskName = new javax.swing.JTextField();
        jLTaskDescription = new javax.swing.JLabel();
        jSPTaskDescription = new javax.swing.JScrollPane();
        jTATaskDescription = new javax.swing.JTextArea();
        jLTaskDueDate = new javax.swing.JLabel();
        jLTaskNotes = new javax.swing.JLabel();
        jSPTaskNotes = new javax.swing.JScrollPane();
        jTATaskNotes = new javax.swing.JTextArea();
        jFTFTaskDueDate = new javax.swing.JFormattedTextField();
        jLMandatoryFieldName = new javax.swing.JLabel();
        jLMandatoryFieldDueDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPTaskToolbar.setBackground(new java.awt.Color(51, 147, 88));

        jLTask.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLTask.setForeground(new java.awt.Color(255, 255, 255));
        jLTask.setText(" Tarefa");

        jLAddTask.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAddTask.setIcon(new javax.swing.ImageIcon("/Users/amandasilva/Documents/Geral/01-Capgemini/LA3/Materiais Compartilhados/resources/check.png")); // NOI18N
        jLAddTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLAddTaskMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPTaskToolbarLayout = new javax.swing.GroupLayout(jPTaskToolbar);
        jPTaskToolbar.setLayout(jPTaskToolbarLayout);
        jPTaskToolbarLayout.setHorizontalGroup(
            jPTaskToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTaskToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLAddTask, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPTaskToolbarLayout.setVerticalGroup(
            jPTaskToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTaskToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPTaskToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTaskToolbarLayout.createSequentialGroup()
                        .addComponent(jLTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jLAddTask, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))
        );

        jPTaskInfos.setBackground(new java.awt.Color(255, 255, 255));

        JLTaskName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        JLTaskName.setForeground(new java.awt.Color(153, 153, 153));
        JLTaskName.setText("Nome");

        jTFTaskName.setBackground(new java.awt.Color(255, 255, 255));
        jTFTaskName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTFTaskName.setForeground(new java.awt.Color(0, 0, 0));
        jTFTaskName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLTaskDescription.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLTaskDescription.setForeground(new java.awt.Color(153, 153, 153));
        jLTaskDescription.setText("Descrição");

        jTATaskDescription.setBackground(new java.awt.Color(255, 255, 255));
        jTATaskDescription.setColumns(20);
        jTATaskDescription.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTATaskDescription.setForeground(new java.awt.Color(0, 0, 0));
        jTATaskDescription.setRows(5);
        jTATaskDescription.setBorder(null);
        jSPTaskDescription.setViewportView(jTATaskDescription);

        jLTaskDueDate.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLTaskDueDate.setForeground(new java.awt.Color(153, 153, 153));
        jLTaskDueDate.setText("Prazo");

        jLTaskNotes.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLTaskNotes.setForeground(new java.awt.Color(153, 153, 153));
        jLTaskNotes.setText("Notas");

        jTATaskNotes.setBackground(new java.awt.Color(255, 255, 255));
        jTATaskNotes.setColumns(20);
        jTATaskNotes.setForeground(new java.awt.Color(0, 0, 0));
        jTATaskNotes.setRows(5);
        jSPTaskNotes.setViewportView(jTATaskNotes);

        jFTFTaskDueDate.setBackground(new java.awt.Color(255, 255, 255));
        jFTFTaskDueDate.setForeground(new java.awt.Color(0, 0, 0));
        jFTFTaskDueDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jLMandatoryFieldName.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jLMandatoryFieldName.setForeground(new java.awt.Color(204, 0, 0));
        jLMandatoryFieldName.setText("Campo nome obrigatorio");

        jLMandatoryFieldDueDate.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jLMandatoryFieldDueDate.setForeground(new java.awt.Color(204, 0, 0));
        jLMandatoryFieldDueDate.setText("Campo prazo obrigatorio");

        javax.swing.GroupLayout jPTaskInfosLayout = new javax.swing.GroupLayout(jPTaskInfos);
        jPTaskInfos.setLayout(jPTaskInfosLayout);
        jPTaskInfosLayout.setHorizontalGroup(
            jPTaskInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTaskInfosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPTaskInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLTaskName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFTaskName)
                    .addComponent(jLTaskDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSPTaskDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addComponent(jLTaskDueDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLTaskNotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSPTaskNotes)
                    .addComponent(jFTFTaskDueDate)
                    .addGroup(jPTaskInfosLayout.createSequentialGroup()
                        .addGroup(jPTaskInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLMandatoryFieldDueDate)
                            .addComponent(jLMandatoryFieldName))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPTaskInfosLayout.setVerticalGroup(
            jPTaskInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTaskInfosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(JLTaskName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLMandatoryFieldName)
                .addGap(28, 28, 28)
                .addComponent(jLTaskDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSPTaskDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLTaskDueDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFTFTaskDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLMandatoryFieldDueDate)
                .addGap(18, 18, 18)
                .addComponent(jLTaskNotes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSPTaskNotes, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPTaskInfos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPTaskToolbar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPTaskToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPTaskInfos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLAddTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAddTaskMouseClicked
        // TODO add your handling code here:
        try {
            
            if(isFieldValid()){
                
                Task task = new Task();
                task.setProject_id(project.getId());
                task.setName(jTFTaskName.getText());
                task.setDescription(jTATaskDescription.getText());
                task.setStatus(false);
                task.setNotes(jTATaskNotes.getText());
                task.setCreatedAt(new Date());
                task.setUpdatedAt(new Date());

                SimpleDateFormat dateFormat = new SimpleDateFormat("y-MM-dd");
                Date dueDate = null;

                try {
                    dueDate = dateFormat.parse(jFTFTaskDueDate.getText());
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(rootPane, ex.getMessage());
                }

                task.setDueDate(dueDate);

                taskController.save(task);

                JOptionPane.showMessageDialog(rootPane, "Tarefa salva com sucesso!!");
                
                this.dispose();
                
            } else {
                hideErrorFields();
                if(jTFTaskName.getText().isEmpty()){
                    jLMandatoryFieldName.setVisible(true);
                }
                
                if(jFTFTaskDueDate.getText().isEmpty()){
                    jLMandatoryFieldDueDate.setVisible(true);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }   
    }//GEN-LAST:event_jLAddTaskMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaskDialogScreen dialog = new TaskDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLTaskName;
    private javax.swing.JFormattedTextField jFTFTaskDueDate;
    private javax.swing.JLabel jLAddTask;
    private javax.swing.JLabel jLMandatoryFieldDueDate;
    private javax.swing.JLabel jLMandatoryFieldName;
    private javax.swing.JLabel jLTask;
    private javax.swing.JLabel jLTaskDescription;
    private javax.swing.JLabel jLTaskDueDate;
    private javax.swing.JLabel jLTaskNotes;
    private javax.swing.JPanel jPTaskInfos;
    private javax.swing.JPanel jPTaskToolbar;
    private javax.swing.JScrollPane jSPTaskDescription;
    private javax.swing.JScrollPane jSPTaskNotes;
    private javax.swing.JTextArea jTATaskDescription;
    private javax.swing.JTextArea jTATaskNotes;
    private javax.swing.JTextField jTFTaskName;
    // End of variables declaration//GEN-END:variables

    public void setProject(Project project) {
        this.project = project;
    }
    
    public void hideErrorFields(){
        jLMandatoryFieldName.setVisible(false);
        jLMandatoryFieldDueDate.setVisible(false);
    }
    
    public boolean isFieldValid(){
        return (!jTFTaskName.getText().isEmpty() && !jFTFTaskDueDate.getText().isEmpty());
    }
    
}
